
GET http://localhost:5000/api/users/


###
GET http://localhost:5000/api/users/2


###
POST http://localhost:5000/api/users/
Content-Type: application/json

{
    "name": "John Doe",
    "email": "test@gmail.com",
    "password": "123456",
    "role": "users"
}

###
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "email": "test@gmail.com",
    "password": "123456"
}

###

PUT http://localhost:5000/api/users/1
Content-Type: application/json

{
    "name": "John Doe",
    "email": "test@gmail.com",
    "password": "1234567",
    "role": "users"
}

###

DELETE http://localhost:5000/api/users/4

###
GET http://localhost:5000/api/projects/

###
GET http://localhost:5000/api/projects/1

###
POST http://localhost:5000/api/projects/
Content-Type: application/json

{
    "thumbnail": "https://imgs.search.brave.com/tm3m5yt4lwYHtnAxa6p8dyQHx079t6p86eW0uiL70NQ/rs:fit:500:0:0/g:ce/aHR0cHM6Ly9zdGF0/aWMuZnJlZWltYWdl/cy5jb20vaW1hZ2Vz/L2hvbWUvYmx1cmJz/L3Zpc3VhbHMud2Vi/cA",
    "title": "Project 3",
    "descriptionIntro": "This is project 3",
    "descriptionMain": "This is project 3",
    "listWord": [
        "React",
        "Node",
        "MongoDB"
    ],
    "illutrations": [
        "https://imgs.search.brave.com/tm3m5yt4lwYHtnAxa6p8dyQHx079t6p86eW0uiL70NQ/rs:fit:500:0:0/g:ce/aHR0cHM6Ly9zdGF0/aWMuZnJlZWltYWdl/cy5jb20vaW1hZ2Vz/L2hvbWUvYmx1cmJz/L3Zpc3VhbHMud2Vi/cA",
        "https://imgs.search.brave.com/tm3m5yt4lwYHtnAxa6p8dyQHx079t6p86eW0uiL70NQ/rs:fit:500:0:0/g:ce/aHR0cHM6Ly9zdGF0/aWMuZnJlZWltYWdl/cy5jb20vaW1hZ2Vz/L2hvbWUvYmx1cmJz/L3Zpc3VhbHMud2Vi/cA",
        "https://imgs.search.brave.com/tm3m5yt4lwYHtnAxa6p8dyQHx079t6p86eW0uiL70NQ/rs:fit:500:0:0/g:ce/aHR0cHM6Ly9zdGF0/aWMuZnJlZWltYWdl/cy5jb20vaW1hZ2Vz/L2hvbWUvYmx1cmJz/L3Zpc3VhbHMud2Vi/cA"
    ],
    
    "link": "https://imgs.search.brave.com/tm3m5yt4lwYHtnAxa6p8dyQHx079t6p86eW0uiL70NQ/rs:fit:500:0:0/g:ce/aHR0cHM6Ly9zdGF0/aWMuZnJlZWltYWdl/cy5jb20vaW1hZ2Vz/L2hvbWUvYmx1cmJz/L3Zpc3VhbHMud2Vi/cA",
    "date": "01/01/2021"
}


###
PUT http://localhost:5000/api/projects/1
Content-Type: application/json

{
    "thumbnail": "https://www.google.com",
    "title": "Project 1",
    "descriptionIntro": "This is project 1",
    "descriptionMain": "This is project 1",
    "listWord": [
        "React",
        "Node",
        "MongoDB"
    ],
    "illutrations": [
        "https://www.google.com",
        "https://www.google.com",
        "https://www.google.com"
    ],
    
    "link": "https://www.google.com"
}

###
DELETE http://localhost:5000/api/projects/2

###
GET http://localhost:5000/api/analysis/

###
GET http://localhost:5000/api/analysis/1

###
POST http://localhost:5000/api/analysis/
Content-Type: application/json

{
    "type": "Project",
    "description": "This is project 1",
    "date": "01/01/2021"
}

###
POST http://localhost:5000/api/presentation/
Content-Type: application/json

{
    "Nom": "Project 1",
    "Prenom": "This is project 1",
    "email": "test@test.fr",
    "Naissance": "01/01/2021",
    "listCompetences": [
        "React",
        "Node",
        "MongoDB"
    ],
    "description": "This is project 1"
}

###
POST http://localhost:5000/api/analysis/search
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6IkpvaG4gRG9lIiwiZW1haWwiOiJ0ZXN0QGdtYWlsLmNvbSIsInJvbGUiOiJ1c2VycyIsImlhdCI6MTcxMzU1MjE0NywiZXhwIjoxNzEzNTUzOTQ3fQ.oI9FQ4Qln_6vh9yX_146r7tVIWtvzK3RE2D_ndUUbGs
Content-Type: application/json

{
    "type": "Project"
}