
GET http://localhost:5000/api/users/


###
GET http://localhost:5000/api/users/2


###
POST http://localhost:5000/api/users/
Content-Type: application/json

{
    "name": "John Doe",
    "email": "test@gmail.com",
    "password": "123456",
    "role": "users"
}

###

PUT http://localhost:5000/api/users/1
Content-Type: application/json

{
    "name": "John Doe",
    "email": "test@gmail.com",
    "password": "1234567",
    "role": "users"
}

###

DELETE http://localhost:5000/api/users/4

###
GET http://localhost:5000/api/projects/

###
GET http://localhost:5000/api/projects/1

###
POST http://localhost:5000/api/projects/
Content-Type: application/json

{
    "thumbnail": "https://www.google.com",
    "title": "Project 2",
    "descriptionIntro": "This is project 1",
    "descriptionMain": "This is project 1",
    "listWord": [
        "React",
        "Node",
        "MongoDB"
    ],
    "illutrations": [
        "https://www.google.com",
        "https://www.google.com",
        "https://www.google.com"
    ],
    
    "link": "https://www.google.com"
}


###
PUT http://localhost:5000/api/projects/1
Content-Type: application/json

{
    "thumbnail": "https://www.google.com",
    "title": "Project 1",
    "descriptionIntro": "This is project 1",
    "descriptionMain": "This is project 1",
    "listWord": [
        "React",
        "Node",
        "MongoDB"
    ],
    "illutrations": [
        "https://www.google.com",
        "https://www.google.com",
        "https://www.google.com"
    ],
    
    "link": "https://www.google.com"
}

###
DELETE http://localhost:5000/api/projects/2
